Fixed docker tag rules

diff --git a/hooks/build b/hooks/build
--- a/hooks/build
+++ b/hooks/build
@@ -7,18 +7,19 @@ then
     POETRY_VERSION="${BASH_REMATCH[1]}"
     printf "Poetry version extracted from tag: $POETRY_VERSION\n"
 else
-    printf "Could not extract poetry version from $SOURCE_BRANCH\n"
+    printf "Could not extract poetry version from SOURCE_BRANCH: $SOURCE_BRANCH\n"
     exit 1
 fi
 
 printf "Building with DOCKER_TAG = $DOCKER_TAG\n"
 
-if [ "$DOCKER_TAG" = "latest" ]; then
+if [ "$DOCKER_TAG" = "latest" || "$DOCKER_TAG" = "python3.8-poetry${POETRY_VERSION}"]; then
     docker build --build-arg PYTHON_VERSION="3.8" --build-arg POETRY_VERSION=${POETRY_VERSION} -t ${IMAGE_NAME} .
-elif [ "$DOCKER_TAG" = "python3.8-poetry${POETRY_VERSION}" ]; then
-    docker build --build-arg PYTHON_VERSION="3.8" --build-arg POETRY_VERSION=${POETRY_VERSION}  -t ${IMAGE_NAME} .
 elif [ "$DOCKER_TAG" = "python3.7-poetry${POETRY_VERSION}" ]; then
     docker build --build-arg PYTHON_VERSION="3.7" --build-arg POETRY_VERSION=${POETRY_VERSION}  -t ${IMAGE_NAME} .
 elif [ "$DOCKER_TAG" = "python3.6-poetry${POETRY_VERSION}" ]; then
     docker build --build-arg PYTHON_VERSION="3.6" --build-arg POETRY_VERSION=${POETRY_VERSION}  -t ${IMAGE_NAME} .
+else
+    printf "No build rule matched DOCKER_TAG: $DOCKER_TAG\n"
+    exit 1
 fi
